# Generated by release script
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE := true
LOCAL_MODULE := nvkeystoregen
LOCAL_SRC_FILES := host/linux-x86/bin/nvkeystoregen
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_REQUIRED_MODULES := libc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE := true
LOCAL_MODULE := nvtegrasign
LOCAL_SRC_FILES := host/linux-x86/bin/nvtegrasign
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_REQUIRED_MODULES := libc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE := true
LOCAL_MODULE := nvtegrasecuretool
LOCAL_SRC_FILES := host/linux-x86/bin/nvtegrasecuretool
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_REQUIRED_MODULES := libc++
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := inv_self_test
LOCAL_SRC_FILES := target/product/shieldtablet/bin/inv_self_test
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := bootloader
LOCAL_MODULE_SUFFIX := .bin
LOCAL_SRC_FILES := target/product/shieldtablet/bootloader.bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := icera_log_serial_arm
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/icera_log_serial_arm
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tlk_daemon
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/tlk_daemon
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc libm libc libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ussrd
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/ussrd
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc++ libgov_graphics libaffinitydaemon libgov_combinator libgov_camera libgov_spincircle libc libgov_boot libphs libm libgov_force libutils libdl libcutils liblog libgov_il libgov_ui libussrd libgov_generic libgov_tbc libgov_gpucompute libaffinitydaemon libc libc++ libcutils libdl liblog libm libussrd libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := pbc
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/pbc
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc++ libm libc libutils libdl libcutils libnativehelper libc libc++ libcutils libdl libm libnativehelper libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := downloader
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/downloader
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := icera-feedback
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/icera-feedback
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := icera-loader
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/icera-loader
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := eks2_client
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/eks2_client
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc++ libm libc libdl libcutils liblog libc libc++ libcutils libdl liblog libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := python
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/python
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := icera-switcherd
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/icera-switcherd
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc++ libm libc libdl libcutils libusbhost libc libc++ libcutils libdl libm libusbhost
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tegrastats
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/tegrastats
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc++ libm libc libnvrm_graphics libutils libdl libcutils liblog libc libc++ libcutils libdl liblog libm libnvrm_graphics libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := raydium_selftest
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/raydium_selftest
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hdcp_test
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/hdcp_test
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := icera-crashlogs
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/icera-crashlogs
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc libc++ libcutils libdl libm libc libc++ libcutils libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := rm_test
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/rm_test
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := btmacwriter
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/btmacwriter
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc libc++ libcutils libdl libm libc libc++ libcutils libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := crash-check-arm
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/crash-check-arm
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvtunerd
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/nvtunerd
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libz libc libnvcameratools libdl libcutils libc libc++ libcutils libdl libm libnvcameratools libnvos libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := rm_ts_server
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/bin/rm_ts_server
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := icera-config
LOCAL_MODULE_SUFFIX := .apk
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/app/icera-config/icera-config.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/app
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := QuadDSecurityService
LOCAL_MODULE_SUFFIX := .apk
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/app/QuadDSecurityService/QuadDSecurityService.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/app
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := NvCecService
LOCAL_MODULE_SUFFIX := .apk
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/app/NvCecService/NvCecService.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/app
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := IceraDebugAgent
LOCAL_MODULE_SUFFIX := .apk
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/app/IceraDebugAgent/IceraDebugAgent.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/app
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_os_eff00000.bin
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/nvavp_os_eff00000.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_os_0ff00000.bin
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/nvavp_os_0ff00000.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := NETB_img.bin
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/gk20a/NETB_img.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware/gk20a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := fecs.bin
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/gk20a/fecs.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware/gk20a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gpccs.bin
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/gk20a/gpccs.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware/gk20a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gpmu_ucode.bin
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/gk20a/gpmu_ucode.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware/gk20a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_aud_ucode.bin
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/nvavp_aud_ucode.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_os_8ff00000.bin
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/nvavp_os_8ff00000.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_os_f7e00000.bin
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/nvavp_os_f7e00000.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_aacdec_ucode.bin
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/nvavp_aacdec_ucode.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_vid_ucode_alt.bin
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/nvavp_vid_ucode_alt.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvavp_mp3dec_ucode.bin
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/nvavp_mp3dec_ucode.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := vic03_ucode.bin
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/tegra12x/vic03_ucode.bin
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware/tegra12x
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvhost_msenc031.fw
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/firmware/tegra12x/nvhost_msenc031.fw
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/firmware/tegra12x
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvoice
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvoice.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libaudioutils libm libc libutils libdl libcutils libicuuc libaudioutils libc libc++ libcutils libdl libicuuc libm libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvwsi
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvwsi.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libphs libnvrm libdl libcutils liblog libnvrm_graphics libnvgr libhardware libsync libc libc++ libcutils libdl libhardware liblog libm libnvgr libnvos libnvrm libnvrm_graphics libphs libsync
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcamlog
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcamlog.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libdl libcutils libc libc++ libcutils libdl libm libnvos
include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := libdrmdecrypt
#LOCAL_MODULE_SUFFIX := .so
#LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libdrmdecrypt.so
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
#LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libstagefright_foundation libdl liblog libnvavp libc libc++ libdl liblog libm libnvavp libnvos libnvrm libstagefright_foundation
#include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcameratools
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcameratools.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libutils libnvos libscf libm libc libnvrm libnvmm_utils libdl libcutils libnvddk_2d_v2 libnvrm_graphics libnvcam_imageencoder libhardware libnvcamerautils libc libc++ libcutils libdl libhardware libm libnvcam_imageencoder libnvcamerautils libnvddk_2d_v2 libnvmm_utils libnvos libnvrm libnvrm_graphics libscf libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvglsi
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvglsi.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvwsi libc++ libm libz libc libdl libcutils libc libc++ libcutils libdl libm libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_08_00_a0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_08_00_a0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvomxadaptor
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvomxadaptor.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libui libmedia libm libc libbinder libutils libdl libcutils libhardware libstagefright libbinder libc libc++ libcutils libdl libhardware libm libmedia libstagefright libui libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvme_msenc
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvme_msenc.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libnvmm_utils libdl libnvrm_graphics libnvddk_2d_v2 libc libc++ libdl libm libnvddk_2d_v2 libnvmm_utils libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libtsec_wrapper
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libtsec_wrapper.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libnvrm_graphics liblog libc libc++ libdl liblog libm libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_08_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_08_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvrm_gpu
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvrm_gpu.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libc libc++ libdl libm libnvos libnvrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvtestresults
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvtestresults.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libnvos libdl libm libc libc++ libdl libm libnvos
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_03_00_a0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_03_00_a0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_04_00_c0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_04_00_c0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcamerautils
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcamerautils.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libnvos libdl libm libc libc++ libdl libm libnvos
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_09_00_c0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_09_00_c0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvvicsi_v3
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvvicsi_v3.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libnvrm_graphics libc libc++ libdl libm libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := liboemcrypto
#LOCAL_MODULE_SUFFIX := .so
#LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/liboemcrypto.so
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
#LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libcutils liblog libtlk_secure_hdcp_up libnvavp
#include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmmlite_video
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmmlite_video.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvmmlite_utils libcuda libnvmmlite libm libc libnvrm libnvmm_utils libdl libcutils libnvtvmr libnvtnr libnvos libnvrm_graphics libnvparser libnvavp libnvddk_2d_v2 libc libc++ libcuda libcutils libdl libm libnvavp libnvddk_2d_v2 libnvmm_utils libnvmmlite libnvmmlite_utils libnvos libnvparser libnvrm libnvrm_graphics libnvtnr libnvtvmr
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvaudiofx
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvaudiofx.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librm_ts_service
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/librm_ts_service.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm_writer
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm_writer.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libnvmm_utils libdl libnvmm_contentpipe libc libc++ libdl libm libnvmm_contentpipe libnvmm_utils libnvos libnvrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvrm
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvrm.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libz libc libutils libdl libcutils libc libc++ libcutils libdl libm libnvos libutils libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmmlite_image
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmmlite_image.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvmmlite_utils libnvtvmr libnvmmlite libm libc libnvrm libnvmm_utils libdl libnvrm_graphics libnvos libnvparser libnvddk_2d_v2 libc libc++ libdl libm libnvddk_2d_v2 libnvmm_utils libnvmmlite libnvmmlite_utils libnvos libnvparser libnvrm libnvrm_graphics libnvtvmr
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvomxilclient
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvomxilclient.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libnvos libdl libm libc libc++ libdl libm libnvos
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libglcore
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libglcore.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libutils vkinfo libm libz libnvrmapi_tegra libvulkan libnvrm libnvgr vulkan.tegra libc libcutils libdl libnvglsi libc libc++ libcutils libdl libm libnvrm libutils libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_il
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_il.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libdl liblog libussrd libc libc++ libdl liblog libm libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_force
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_force.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libdl liblog libussrd libc libc++ libdl liblog libm libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvstitching
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvstitching.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := liblog libopencv24_tegra liblog libopencv24_tegra
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/libnvstitching.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm_camera_v3
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm_camera_v3.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvcamlog libutils libnvos libnvddk_2d_v2 libnvtvmr libnvisp_v3 libgui libbinder libnvmm libandroid libGLESv2 libdl libnvmm_utils libnvrm_graphics libnvvicsi_v3 libnvcamerautils libEGL libcuda libjpeg libnvrm libcutils libopencv24_tegra libnvodm_imager libEGL libGLESv2 libandroid libbinder libcuda libcutils libdl libgui libjpeg libnvcamerautils libnvcamlog libnvddk_2d_v2 libnvisp_v3 libnvmm libnvmm_utils libnvodm_imager libnvos libnvrm libnvrm_graphics libnvtvmr libnvvicsi_v3 libopencv24_tegra libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_02_00_20
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_02_00_20.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvrmapi_tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvrmapi_tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libz libc libdl libnvrm_graphics libc libc++ libdl libm libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvtvmr
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvtvmr.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libnvrm_graphics libnvavp libnvddk_2d_v2 libc libc++ libdl libm libnvavp libnvddk_2d_v2 libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libscf
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libscf.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvcamlog libutils libnvmm_camera_v3 libsync libnvtvmr libnvisp_v3 libnvfnetstorehdfx libgui libphs libbinder libprotobuf-cpp-lite libdl libopencv24_tegra libandroid libGLESv2 libnvfnet libm libc libnvvicsi_v3 libnvmm_utils libnvrm_graphics libnvos libnvcamerautils libEGL libcuda libnvrm libcutils libnvddk_vic libnvfnetstoredefog libnvodm_imager libEGL libGLESv2 libandroid libbinder libc libc++ libcuda libcutils libdl libgui libm libnvcamerautils libnvcamlog libnvddk_vic libnvfnet libnvfnetstoredefog libnvfnetstorehdfx libnvisp_v3 libnvmm_camera_v3 libnvmm_utils libnvodm_imager libnvos libnvrm libnvrm_graphics libnvtvmr libnvvicsi_v3 libopencv24_tegra libphs libprotobuf-cpp-lite libsync libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_02_00_a0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_02_00_a0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librm31080
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/librm31080.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcam_imageencoder
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcam_imageencoder.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvtvmr libnvos libm libc libjpeg libnvrm libnvmm_utils libdl libc libc++ libdl libjpeg libm libnvmm_utils libnvos libnvrm libnvtvmr
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/libnvcam_imageencoder.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_0a_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_0a_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmmlite_utils
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmmlite_utils.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libnvmm_utils libdl libnvrm_graphics libc libc++ libdl libm libnvmm_utils libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _socket
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/_socket.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := cmath
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/cmath.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := strop
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/strop.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := select
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/select.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _struct
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/_struct.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _multibytecodec
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/_multibytecodec.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _collections
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/_collections.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := time
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/time.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _functools
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/_functools.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _nvcameratools
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/_nvcameratools.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libpython2.6 libc libnvcameratools libdl libc libc++ libdl libm libnvcameratools libnvos libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := datetime
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/datetime.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _fileio
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/_fileio.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := unicodedata
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/unicodedata.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := fcntl
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/fcntl.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _random
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/_random.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := array
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/array.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := operator
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/operator.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := binascii
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/binascii.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := parser
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/parser.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := _weakref
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/python2.6/lib-dynload/_weakref.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/python2.6/lib-dynload
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libpython2.6 libc libc++ libdl libm libpython2.6
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_03_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_03_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libril-icera
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libril-icera.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libutils libcrypto libm libc libnetutils libril libdl libcutils librilutils libc libc++ libcrypto libcutils libdl libm libnetutils libril librilutils libutils
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/libril-icera.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_tbc
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_tbc.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libdl liblog libussrd libc libc++ libdl liblog libm libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_08_00_20
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_08_00_20.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvwinsys
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvwinsys.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libui libnvos libm libc libbinder libnvrm libutils libgui libcutils libdl libbinder libc libc++ libcutils libdl libgui libm libnvos libnvrm libui libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libussrd
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libussrd.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libaffinitydaemon libm libc libbinder libutils libdl libcutils liblog libnvos libaffinitydaemon libbinder libc libc++ libcutils libdl liblog libm libnvos libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libnvmm_utils libdl libnvrm_graphics libc libc++ libdl libm libnvmm_utils libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := libwvm
#LOCAL_MODULE_SUFFIX := .so
#LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libwvm.so
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
#LOCAL_REQUIRED_MODULES := libc++ libmedia libnvos libm libWVStreamControlAPI_L1 libc libbinder libnvrm libstagefright_foundation libutils libdl libcutils libdrmframework libz liblog libnvavp libstagefright libWVStreamControlAPI_L1 libbinder libc libc++ libcutils libdl libdrmframework liblog libm libmedia libnvavp libnvos libnvrm libstagefright libstagefright_foundation libutils libz
#include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libtsechdcp
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libtsechdcp.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libcutils liblog libnvrm_graphics libc libc++ libcutils libdl liblog libm libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := libdrmwvmplugin
#LOCAL_MODULE_SUFFIX := .so
#LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/drm/libdrmwvmplugin.so
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/drm
#LOCAL_REQUIRED_MODULES := libc++ libnvos libm libWVStreamControlAPI_L1 libc libbinder libnvrm libutils libdl libcutils liblog libz libnvavp libwvdrm_L1 libWVStreamControlAPI_L1 libbinder libc libc++ libcutils libdl liblog libm libnvavp libnvos libnvrm libutils libwvdrm_L1 libz
#include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libcuda
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libcuda.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libz libc libphs libnvidia-ptxjitcompiler libdl liblog libnvidia-fatbinaryloader libc libc++ libdl liblog libm libphs libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_spincircle
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_spincircle.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libdl liblog libussrd libc libc++ libdl liblog libm libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_04_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_04_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libphs
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libphs.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libbinder libutils libdl libcutils liblog libbinder libc libc++ libcutils libdl liblog libm libnvos libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_05_00_c0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_05_00_c0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_camera
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_camera.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libdl liblog libussrd libc libc++ libdl liblog libm libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := samples
LOCAL_MODULE := libnvcap
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcap.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libstdc++ libmedia libnvos libm libc libbinder libnvcapclk libnvrm libnvmm_utils libdl libcutils liblog libnvhdcp libnvrm_graphics libutils libbinder libc libc++ libcutils libdl liblog libm libmedia libnvcapclk libnvhdcp libnvmm_utils libnvos libnvrm libnvrm_graphics libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvfnetstorehdfx
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvfnetstorehdfx.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvfnet libnvos libm libc libdl
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := samples
LOCAL_MODULE := libnvcapclk
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcapclk.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libbinder libnvrm libutils libdl libnvrm_graphics libnvddk_2d_v2 libbinder libc libc++ libdl libm libnvddk_2d_v2 libnvos libnvrm libnvrm_graphics libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libpython2.6
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libpython2.6.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := samples
LOCAL_MODULE := libnvhrcv
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvhrcv.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libstdc++ libmedia libnvos libm libc libbinder libnvcapclk libnvrm libnvmm_utils libdl libcutils liblog libnvrm_graphics libutils libbinder libc libc++ libcutils libdl liblog libm libmedia libnvcapclk libnvmm_utils libnvos libnvrm libnvrm_graphics libstdc++ libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm_parser
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm_parser.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libnvmm_utils libdl libnvmm_contentpipe libc libc++ libdl libm libnvmm_contentpipe libnvmm_utils libnvos libnvrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_02_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_02_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm_contentpipe
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm_contentpipe.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libnvmm_utils libdl libnvrm_graphics libc libc++ libdl libm libnvmm_utils libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libclcore_nvidia
LOCAL_MODULE_SUFFIX := .bc
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libclcore_nvidia.bc
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_STRIP_MODULE := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvblit
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvblit.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm_gpu libnvrm libdl libnvrm_graphics liblog libnvddk_vic libnvgr libhardware libsync libc libc++ libdl libhardware liblog libm libnvddk_vic libnvgr libnvos libnvrm libnvrm_gpu libnvrm_graphics libsync
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_generic
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_generic.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libdl liblog libussrd libc libc++ libdl liblog libm libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmmlite_audio
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmmlite_audio.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvmmlite_utils libnvmmlite libm libc libnvrm libnvmm_utils libdl libnvrm_graphics libnvos libc libc++ libdl libm libnvmm_utils libnvmmlite libnvmmlite_utils libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvhwc_service
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvhwc_service.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libbinder libutils libdl libcutils libbinder libc libc++ libcutils libdl libm libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_07_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_07_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := keystore.tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/keystore.tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libc libc++ liblog libdl libm libc libc++ libdl liblog libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hwcomposer.tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/hwcomposer.tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libc++ libEGL libnvhwc_service libnvos libui libm libGLESv2 libc libnvrm libutils libdl libcutils liblog libnvblit libtlk_secure_hdcp_up libnvrm_graphics libnvddk_vic libnvgr libhardware libsync libEGL libGLESv2 libc libc++ libcutils libdl libhardware liblog libm libnvblit libnvddk_vic libnvgr libnvhwc_service libnvos libnvrm libnvrm_graphics libsync libtlk_secure_hdcp_up libui libutils
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/hw/hwcomposer.tegra.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := ts.default
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/ts.default.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := memtrack.tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/memtrack.tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libc++ libm libc libdl libcutils liblog libc libc++ libcutils libdl liblog libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := vulkan.tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/vulkan.tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libc++ libEGL libm libc libdl liblog libEGL libc libc++ libdl liblog libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := audio.primary.tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/audio.primary.tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libc++ libaudioutils libmedia libnvos libm libc libexpat libnbaio libbinder libtinyalsa libutils libdl libcutils libnvaudiofx libnvoice libtinycompress libaudiospdif libicuuc libaudiospdif libaudioutils libbinder libc libc++ libcutils libdl libexpat libicuuc libm libmedia libnbaio libnvaudiofx libnvoice libnvos libtinyalsa libtinycompress libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gralloc.tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/gralloc.tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libcutils liblog libnvblit libnvrm_graphics libnvgr libsync libc libc++ libcutils libdl liblog libm libnvblit libnvgr libnvos libnvrm libnvrm_graphics libsync
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := camera.tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/hw/camera.tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/hw
LOCAL_REQUIRED_MODULES := libc++ libmedia libnvcamlog libutils libnvgr libnvddk_2d_v2 libcameraservice libnvtvmr libnvos libgui libbinder libnvcam_imageencoder libdl libnvmm libandroid libGLESv2 libscf libm libhardware_legacy libc libnvmm_utils libnvrm_graphics libcamera_metadata libui libjpeg libnvrm libnvcamerahdr_v3 libcutils libpowermanager libhardware libGLESv2 libandroid libbinder libc libc++ libcamera_metadata libcameraservice libcutils libdl libgui libhardware libhardware_legacy libjpeg libm libmedia libnvcam_imageencoder libnvcamerahdr_v3 libnvcamlog libnvddk_2d_v2 libnvgr libnvmm libnvmm_utils libnvos libnvrm libnvrm_graphics libnvtvmr libpowermanager libscf libui libutils
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/hw/camera.tegra.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm_audio
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm_audio.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libnvmm_utils libdl libnvrm_graphics libnvmm libc libc++ libdl libm libnvmm libnvmm_utils libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvrm_graphics
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvrm_graphics.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl liblog libsync libc libc++ libdl liblog libm libnvos libnvrm libsync
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_03_00_20
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_03_00_20.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libstagefright_hdcp
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libstagefright_hdcp.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libnvrm libstagefright_foundation libutils libdl liblog libc libc++ libdl liblog libm libnvrm libstagefright_foundation libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libtlk_secure_hdcp_up
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libtlk_secure_hdcp_up.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm_graphics libtsechdcp libdl libcutils liblog libc libc++ libcutils libdl liblog libm libnvos libnvrm_graphics libtsechdcp
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmm_utils
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmm_utils.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libcutils libnvrm_graphics libnvavp libc libc++ libcutils libdl libm libnvavp libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvddk_vic
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvddk_vic.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libnvrm_graphics liblog libnvgr libsync libc libc++ libdl liblog libm libnvgr libnvos libnvrm libnvrm_graphics libsync
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_gpucompute
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_gpucompute.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libdl liblog libussrd libc libc++ libdl liblog libm libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvomx
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvomx.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libmedia libutils libnvgr libnvddk_2d_v2 libsync libnvtvmr libnvos libbinder libdl libnvmm libnvmmlite libm libc libnvmm_utils libnvrm_graphics libOpenSLES libnvmmlite_utils libui libnvrm libcutils libnvmm_contentpipe libpowermanager libhardware libOpenSLES libbinder libc libc++ libcutils libdl libhardware libm libmedia libnvddk_2d_v2 libnvgr libnvmm libnvmm_contentpipe libnvmm_utils libnvmmlite libnvmmlite_utils libnvos libnvrm libnvrm_graphics libnvtvmr libpowermanager libsync libui libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_0b_00_a0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_0b_00_a0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_ui
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_ui.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libaffinitydaemon libm libc libdl liblog libussrd libaffinitydaemon libc libc++ libdl liblog libm libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := tests
LOCAL_MODULE := libnvos
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvos.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libdl libcutils liblog libc libc++ libcutils libdl liblog libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := samples
LOCAL_MODULE := libnvhdcp
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvhdcp.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libnvmm_utils libdl libcutils libnvrm_graphics libc libc++ libcutils libdl libm libnvmm_utils libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_06_00_b0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_06_00_b0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvddk_2d_v2
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvddk_2d_v2.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libnvrm_graphics libnvddk_vic libc libc++ libdl libm libnvddk_vic libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvavp
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvavp.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libc libc++ libdl libm libnvos libnvrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvisp_v3
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvisp_v3.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libnvrm_graphics libc libc++ libdl libm libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcamerahdr_v3
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcamerahdr_v3.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libnvos libnvrm libnvmm_utils libcutils libopencv24_tegra libnvcameranrr libnvcamerautils libcutils libnvcameranrr libnvcamerautils libnvmm_utils libnvos libnvrm libopencv24_tegra
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/vendor/lib/libnvcamerahdr_v3.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_09_02_c0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_09_02_c0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvparser
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvparser.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libc libc++ libdl libm libnvos libnvrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libaffinitydaemon
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libaffinitydaemon.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libutils libdl libcutils liblog libc libc++ libcutils libdl liblog libm libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvodm_imager
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvodm_imager.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libnvcamlog libdl libcutils liblog libnvrm_graphics libnvcamerautils libc libc++ libcutils libdl liblog libm libnvcamerautils libnvcamlog libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_graphics
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_graphics.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libutils libdl libcutils liblog libussrd libc libc++ libcutils libdl liblog libm libussrd libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcms
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvcms.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libnvrm_graphics liblog libc libc++ libdl liblog libm libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvfnet
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvfnet.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libEGL libnvos libm libc libexpat libnvrm libdl libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvmmlite
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvmmlite.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvmmlite_utils libnvos libm libc libnvmm_utils libdl libc libc++ libdl libm libnvmm_utils libnvmmlite_utils libnvos
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvgr
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvgr.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libdl libcutils libhardware libsync libc libc++ libcutils libdl libhardware libm libsync
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvtnr
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libnvtnr.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvtvmr libnvos libm libc libnvrm libdl libnvrm_graphics libc libc++ libdl libm libnvos libnvrm libnvrm_graphics libnvtvmr
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgov_boot
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libgov_boot.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libdl liblog libussrd libc libc++ libdl liblog libm libussrd
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := para_10_09_01_c0
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/para_10_09_01_c0.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libstagefrighthw
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/libstagefrighthw.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libm libc libutils libdl liblog libc libc++ libdl liblog libm libutils
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libGLESv2_tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/egl/libGLESv2_tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/egl
LOCAL_REQUIRED_MODULES := libc++ libglcore libnvos libm libc libnvrm libdl libnvrm_graphics libc libc++ libdl libglcore libm libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libGLESv1_CM_tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/egl/libGLESv1_CM_tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/egl
LOCAL_REQUIRED_MODULES := libc++ libglcore libnvos libm libc libnvrm libdl libnvrm_graphics libc libc++ libdl libglcore libm libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libEGL_tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/vendor/lib/egl/libEGL_tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib/egl
LOCAL_REQUIRED_MODULES := libc++ libm libz libc libphs libdl libcutils libnvglsi libsync libc libc++ libcutils libdl libm libsync libz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libsensors.prefusion.mpl520.nvs
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libsensors.prefusion.mpl520.nvs.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libdl libmplmpu libmllite libsensors.hal.nvs libc libc++ libdl libm libmllite libmplmpu libnvos libsensors.hal.nvs
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := liboemcrypto
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/liboemcrypto.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libnvrm libdl libcutils liblog libtlk_secure_hdcp_up libnvavp libc libc++ libcutils libdl liblog libm libnvavp libnvos libnvrm libtlk_secure_hdcp_up
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libsensors.fusion.mpl520.nvs
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libsensors.fusion.mpl520.nvs.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES := inv_self_test libc++ libm libsensors.prefusion.mpl520.nvs libc libdl libsensors.hal.nvs libc libc++ libdl libm libsensors.hal.nvs libsensors.prefusion.mpl520.nvs
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libmplmpu
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libmplmpu.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcameraframedata
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvcameraframedata.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvchimerashaderstore
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvchimerashaderstore.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libhdcp_up
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libhdcp_up.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvviccomposer
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvviccomposer.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvfnet
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvfnet.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libEGL libnvos libm libc libexpat libnvrm libdl libnvrm_graphics libEGL libc libc++ libdl libexpat libm libnvos libnvrm libnvrm_graphics
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcamerahdr_expfusion_v3
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvcamerahdr_expfusion_v3.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcameradata
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvcameradata.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvgpudenoise
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvgpudenoise.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := sensors.default.api_v1.3.mpl520.nvs
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/hw/sensors.default.api_v1.3.mpl520.nvs.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib/hw
LOCAL_REQUIRED_MODULES := libc++ libsensors.hal-drivers.nvs libnvos libm libc libdl libsensors.fusion.mpl520.nvs libsensors.hal.nvs libc libc++ libdl libm libnvos libsensors.fusion.mpl520.nvs libsensors.hal-drivers.nvs libsensors.hal.nvs
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvfnetstorehdfx
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvfnetstorehdfx.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/vendor/lib
LOCAL_REQUIRED_MODULES := libc++ libnvfnet libnvos libm libc libdl libc libc++ libdl libm libnvfnet libnvos
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libmonitor
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libmonitor.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libnvcudaslidingdct
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libnvcudaslidingdct.a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/lib/libnvcudaslidingdct.a_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := libtbb
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libtbb.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES := out/target/product/shieldtablet/system/lib/libtbb.so 
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/lib/libtbb.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := libmllite
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libmllite.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES := libc libc++ libnvos libdl libm libc libc++ libdl libm libnvos
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libsensors.hal-drivers.nvs
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libsensors.hal-drivers.nvs.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES := libc++ libnvos libm libc libdl libsensors.hal.nvs libc libc++ libdl libm libnvos libsensors.hal.nvs
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libsensors.hal.nvs
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libsensors.hal.nvs.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES := libc libc++ libnvos libdl libm libc libc++ libdl libm libnvos
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libopencv24_tegra
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := target/product/shieldtablet/lib/libopencv24_tegra.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES := libEGL libGLESv2 libdl libjpeg liblog libz libpng libtbb libEGL libGLESv2 libdl libjpeg liblog libpng libtbb libz
include $(BUILD_PREBUILT)
LOCAL_PREBUILT_NOTICE_FILE := target/product/shieldtablet/lib/libopencv24_tegra.so_NOTICE
include $(NVIDIA_PREBUILT_NOTICE)

include $(CLEAR_VARS)
LOCAL_MODULE := warmboot
LOCAL_MODULE_SUFFIX := .bin
LOCAL_SRC_FILES := target/product/shieldtablet/warmboot.bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvbdktestbl
LOCAL_MODULE_SUFFIX := .bin
LOCAL_SRC_FILES := target/product/shieldtablet/nvbdktestbl.bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hdcp2x.srm
LOCAL_SRC_FILES := target/product/shieldtablet/etc/hdcpsrm/hdcp2x.srm
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/hdcpsrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hdcp1x.srm
LOCAL_SRC_FILES := target/product/shieldtablet/etc/hdcpsrm/hdcp1x.srm
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/hdcpsrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hdcp2xtest.srm
LOCAL_SRC_FILES := target/product/shieldtablet/etc/hdcpsrm/hdcp2xtest.srm
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/hdcpsrm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tegra_xusb_firmware
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/tegra_xusb_firmware
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvhost_tsec.fw
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/tegra12x/nvhost_tsec.fw
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware/tegra12x
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tegra12x_xusb_firmware
LOCAL_SRC_FILES := target/product/shieldtablet/etc/firmware/tegra12x_xusb_firmware
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/etc/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tos
LOCAL_MODULE_SUFFIX := .img
LOCAL_SRC_FILES := target/product/shieldtablet/tos.img
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := secure_otf
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/secure_otf_intermediates/secure_otf
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := crypto_service
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/crypto_service_intermediates/crypto_service
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := eks2_service
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/eks2_service_intermediates/eks2_service
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := oemcrypto_secure_service
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/oemcrypto_secure_service_intermediates/oemcrypto_secure_service
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := trusted_app
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/trusted_app_intermediates/trusted_app
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hwkeystore_task
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/hwkeystore_task_intermediates/hwkeystore_task
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := secure_rtc
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/secure_rtc_intermediates/secure_rtc
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := storage_service
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/storage_service_intermediates/storage_service
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hdcp_secure_service
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/hdcp_secure_service_intermediates/hdcp_secure_service
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tlkstoragedemo_task
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/tlkstoragedemo_task_intermediates/tlkstoragedemo_task
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := trusted_app2
LOCAL_SRC_FILES := target/product/shieldtablet/obj/EXECUTABLES/trusted_app2_intermediates/trusted_app2
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvtboot
LOCAL_MODULE_SUFFIX := .bin
LOCAL_SRC_FILES := target/product/shieldtablet/nvtboot.bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvtboot_recovery
LOCAL_MODULE_SUFFIX := .bin
LOCAL_SRC_FILES := target/product/shieldtablet/nvtboot_recovery.bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_REQUIRED_MODULES := libc libc++ libdl libm libc libc++ libdl libm
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
include $(BUILD_COPY_HEADERS)
